## Data Transformation Parameters

IMPUTER_STRATEGY: most_frequent
TEST_SIZE: 0.25
RANDOM_STATE: 42
COLS_TO_DROP:
  - web_traffic
  - Statistical_report
  - Links_pointing_to_page
  - RightClick
  - port
  - double_slash_redirecting
  - Iframe
  - popUpWidnow
  - on_mouseover
  - Submitting_to_email
  - Abnormal_URL
TARGET: Result

## Model Training Parameters

max_depth: 1
min_samples_leaf: 1
min_samples_split: 2
n_estimators: 100

## Model Evaluation Params
registered_model_name : RandomForestClassifier