artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://archive.ics.uci.edu/ml/machine-learning-databases/00327/Training%20Dataset.arff
  local_data_dir_path: artifacts/data_ingestion/local_data
  processed_data_dir_path : artifacts/data_ingestion/processed_data
  local_data_file_path: artifacts/data_ingestion/local_data/data.arff
  processed_data_file_path : artifacts/data_ingestion/processed_data/data.csv

data_validation:

  root_dir : artifacts/data_validation
  processed_data_file_path : artifacts/data_ingestion/processed_data/data.csv
  validation_report_dir_path: artifacts/data_validation/validation_report
  validation_report_file_path: artifacts/data_validation/validation_report/report.json
  schema: 
    columns: 
      having_IP_Address: int64          
      URL_Length: int64         
      Shortining_Service: int64         
      having_At_Symbol: int64  
      double_slash_redirecting: int64   
      Prefix_Suffix: int64
      having_Sub_Domain: int64       
      SSLfinal_State: int64   
      Domain_registeration_length: int64
      Favicon: int64
      port: int64             
      HTTPS_token: int64                
      Request_URL: int64         
      URL_of_Anchor: int64         
      Links_in_tags: int64       
      SFH: int64       
      Submitting_to_email: int64        
      Abnormal_URL: int64 
      Redirect: int64        
      on_mouseover: int64            
      RightClick: int64        
      popUpWidnow: int64          
      Iframe: int64         
      age_of_domain: int64              
      DNSRecord: int64       
      web_traffic: int64           
      Page_Rank: int64         
      Google_Index: int64           
      Links_pointing_to_page: int64     
      Statistical_report: int64
      Result: int64

    no_of_rows: 11055
    no_of_cols: 31

data_transformation:

  root_dir: artifacts/data_transformation
  data_validation_report: artifacts/data_validation/validation_report/report.json
  processed_data_file_path : artifacts/data_ingestion/processed_data/data.csv
  transformed_data_dir_path: artifacts/data_transformation/transformed_data
  transformed_data_file_path: artifacts/data_transformation/transformed_data/transformed_data.csv
  train_test_data_dir_path: artifacts/data_transformation/train_test_data
  x_train_file_path: artifacts/data_transformation/train_test_data/x_train.csv
  x_test_file_path: artifacts/data_transformation/train_test_data/x_test.csv
  y_train_file_path: artifacts/data_transformation/train_test_data/y_train.csv
  y_test_file_path: artifacts/data_transformation/train_test_data/y_test.csv
